[workspace]
members = [
"crates/core",
"crates/search",
]

[workspace.package]
version = "0.1.2"
description = "This is my education project."
authors = ["Mike <mikepodkoptop@gmail.com>"]
license = "MIT"