[package]
name = "core-grep"
version = "0.1.7"
edition = "2021"
description = "This is core grep project."
authors = ["Mike <mikepodkoptop@gmail.com>"]
license = "MIT"

[dependencies]
grep-search = { version = "0.1.4", path = "../search"}

[[bin]]
bench = false
path = "src/main.rs"
name = "grep"